[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
config.requireConfiguration = true

[[language]]
name = "python"
language-servers = ["ty", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
roots = ["pyproject.toml", "uv.lock"]

[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = [
    'format',
  ] },
  "tailwindcss",
]
roots = ["biome.json", "biome.jsonc"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path=file.ts",
] }

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "tailwindcss",
]
roots = ["biome.json", "biome.jsonc"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path=file.tsx",
] }

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = [
    'format',
  ] },
]
roots = ["biome.json", "biome.jsonc"]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path=file.json",
] }

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "tailwindcss",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "tailwindcss",
]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss"]
